### ISSUE TITLE
RetrieveEntityRequest

### ISSUE THREAD

**Issue by Kraviecc** [jordimontana82/fake-xrm-easy#187]
Hi,
Is it possible to test RetrieveEntityRequest? At this moment I'm getting "The specified entity name wasn't found in the metadata cache".

**Comment by jordimontana82** [comment]
Hi Kraviecc. It is. But you need to inject your entity metadata, that's why you got the error, because it couldn't find any entity with that the entity name.

[Pls see this Example](https://github.com/jordimontana82/fake-xrm-easy/blob/a43cb03fdd1a3e2d7d8a519bd835f5f1ab5133a9/FakeXrmEasy.Tests.Shared/FakeContextTests/RetrieveEntityRequestTests/RetrieveEntityRequestTests.cs#L72-L96)

**Comment by Kraviecc** [comment]
Hi Jordi,
thank you, I made it based on the example you provided. To be more precisely, I used the one which is under the test you showed me:

> When_calling_retrieve_entity_with_a_fake_attribute_definition_it_is_returned
