### ISSUE TITLE
Test set Opportunity Won issue

### ISSUE THREAD

**Issue by gperezhdz** [jordimontana82/fake-xrm-easy#192]
I am using FakeXrmEasy framework to test my plugin that sets an opportunity as won, 
but it shows me a message "FakeXrmEasy.PullRequestException: Exception: The organization request type 'Microsoft.Crm.Sdk.Messages.WinOpportunityRequest"

What do you recommend?

**Comment by jordimontana82** [comment]
Hi @gperezhdz !

Thanks for raising this. Indeed so that request is not yet implemented, but it could be implemented easily.

According to the [msdn description of that message](https://msdn.microsoft.com/en-us/library/microsoft.crm.sdk.messages.winopportunityrequest.aspx), the message mainly needs the opportunity id and the won status. So it is essentially doing kind of a SetStateRequest internally which could be implemented as a new fake message executor by just doing an update.

Feel free to implement it and issue a PR please! 

You can start from a message like [this one](https://github.com/jordimontana82/fake-xrm-easy/blob/master/FakeXrmEasy.Shared/FakeMessageExecutors/AddMemberListRequestExecutor.cs) as an example.

I would implement it like this:

1) Check the OpportunityClose parameter was passed as it is required
2) Check the Status parameter was passed as it is required
3) Check the opportunity record exists
4) Update the opportunity's statuscode field with the one from the parameter (via just service.Update)
5) Return a pretty much blank [WinOpportunityResponse](https://msdn.microsoft.com/en-us/library/microsoft.crm.sdk.messages.winopportunityresponse.aspx) (which, surprisingly, it doesn't return anything, it probably just raises an exception if something was wrong... :P )

If you do it the TDD way (which I hope! ;)), then please start with a new test in the FakeXrmEasy.Tests.Shared project, and gradually start implementing the actual logic in the FakeXrmEasy.Shared project. Then back to a new test, then code, etc...

Hope this helps!

**Comment by gperezhdz** [comment]
Hi Jordi, 
After I created the WinOpportunityRequestExecutor , How can I test it ?

**Comment by jordimontana82** [comment]
Hi @gperezhdz 

Any luck with this? :)
