### ISSUE TITLE
Add SetStateRequest implementation

### ISSUE THREAD

**Issue by kmjones77** [jordimontana82/fake-xrm-easy#20]
As it is not possible to assign the statecode of an entity, if would be useful to have an implementation of the SetStateRequest so we could activate / deactivate entities as below

https://csharpsql.wordpress.com/2014/11/18/activate-deactivate-an-entity-in-crm-using-c/

**Comment by jordimontana82** [comment]
Hi Ken,

Good spot :)

Will add it soon, but before that, I refactored the FakeExecute method into a set of IFakeMessageExecutor classes we can easily extend in future.

@DigitalFlow , I added a new Dictionary, FakeMessageExecutors, which was similar to your ExecutionMocks one, but we needed to pass not only the OrganizationRequest but also the XrmFakedContext to execute most of them so that's why I added a method using an interface + class as opposed to just the delegate.

I kept the ExecutionMocks property just because if I remove it, your tests will break. Are you happy to go with the new Dictionary only?

**Comment by DigitalFlow** [comment]
Hey @jordimontana82,

looks good to me, will adjust to that.

**Comment by jordimontana82** [comment]
Great :+1:

**Comment by jordimontana82** [comment]
We need to default the statecode on the Initialize method too.

**Comment by kmjones77** [comment]
Have you pushed the code to nuget?

**Comment by jordimontana82** [comment]
It is there now, yep :)
