### ISSUE TITLE
Consider using Shared Projects

### ISSUE THREAD

**Issue by daryllabar** [jordimontana82/fake-xrm-easy#21]
Shared projects remove the need to have the linked files everywhere that you currently have.

[2 Minute Example Video](http://screencast.com/t/OK5299AjrG6
)

**Comment by jordimontana82** [comment]
Cool video :+1: 

Agree, when this project started on VS2013 Community that Shared Projects functionality (introduced after Update 2) wasn't there yet so the linked file was the only reasonable solution.

Will change the structure to use this, specially, because the project keeps growing and growing.

Cheers!

**Comment by daryllabar** [comment]
Glad you found it helpful!
I noticed you have all of your NuGet Packages separated by year.  Any reason of doing that vs potentially having one, that followed the Major Versioning of the Xrm SDK (6,7,8)?


Date: Wed, 3 Feb 2016 14:33:28 -0800

**Comment by jordimontana82** [comment]
Good question.

We indeed use Semantic Versioning like the following:
{Major}-{Minor}-{Patches}-{Build no.}

But our lifecycle it's different than the CRM sdk. Example: just added a new feature to fake a SetStateRequest message, technically, it is not a breaking change (major) but a new feature of the library (minor), although they target the same CRM SDK versions.
