### ISSUE TITLE
XrmOrderByAttributeComparer - better exception in case of comparing EntityReference

### ISSUE THREAD

**Issue by mivra** [jordimontana82/fake-xrm-easy#215]
Hi Jordi, 
we ran into an issue with one of our queries. It was throwing NullReferenceException in order by expression. After an examination, one can say it was "by design" behavior, but the message was really unfriendly to the end user. I pushed a commit with better exception message into my fork here:
https://github.com/mivra/fake-xrm-easy/commit/7b6e73493cdd7f55d273a0550b36f43de0a85c78

Few questions:
1) FakeXrmEasy should mimic the behavior of the true CRM, so I believe replacing null with an empty string is not a good idea, right?
2) Is there any specific exception type you would suggest to throw instead of general Exception?
3) Possibly the framework could retrieve the related entity and get Name field from it. But the value still could be null, but in that case replacing by empty string would be ok. What do you think?

Thanks,
Michal

**Comment by jordimontana82** [comment]
Hi Michal,

Thanks for this. I think it should be possible to sort values even if null, so I wouldn't raise an exception for this. I think if you sort ascending by an attribute in CRM with null values, these values come first, before anything else (non null ones). 

Maybe just do something similar to the first part of the function, which deals with nulls, and do the same for the Name property:


    if (entityRefA.Name == null && entityRefB.Name == null) return 0;  //Equal

            if (entityRefA.Name == null)
                return -1;
            if (entityRefB.Name == null)
                return 1;

        return (entityRefA.Name.CompareTo(entityRefB.Name));

In relation to the last point, about populating the .Name property,  I'm thinking of 2 options.

1. Populate it manually in your test as part of .Initialize.  Which is not a bad idea either, cause you'll need to setup these properties only when you need to test anything against them.

2. Whenever you create / edit a record with an EntityReference, we populate the name column based on the record's primary field. But we need some sort of metadata to achieve this to know which is the primary field for that entity. We could use MetadataDictionary and .InitializeMetadata to achieve this.

So maybe we could check if there is any metadata for the entity, and then use Option 2. Otherwise, just rely on Option 1. And implement issue #204 along with this approach.

Thoughts?

**Comment by mivra** [comment]
I confirm, that there can be a valid situation, where EntityReference leads to an entity whose primary name value is null. Therefore this has to be considered as a valid scenario and implemented as you described. What I don't like about it, is that usually the EntityReferences just won't be initialized properly (with Names) in the test context. But fortunately ordering by EntityReference is not that common and the part 2 - populating the Name column - solves this well (really like how it complements with the issue #204). The tricky part will be how to manage updates - if the entity name value changes all EntityReferences pointing to it needs to be changed also.
Shall I implement the part 1 in my branch? Unfortunately, I'm not up to implement the part 2 :/

**Comment by jordimontana82** [comment]
Part 2 shouldn't be much complex provided metadata is also used and initialised with .InitializeMetadata. The name of the attribute which needs to be populated into the lookup could be retrieved from [the PrimaryNameAttribute field](https://msdn.microsoft.com/en-us/library/microsoft.xrm.sdk.metadata.entitymetadata.primarynameattribute.aspx) 

Thing is we are kind of forcing to use metadata (which is not too bad either) if you want this to be automatically populated. Or, if not using metadata, just go for Part 1.

What do you think?
