### ISSUE TITLE
InvalidCastException with response from InitializeFromRequest 

### ISSUE THREAD

**Issue by bwmodular** [jordimontana82/fake-xrm-easy#249]
Hi Jordi,
hope all's good with you.

I'm encountering an issue with the response from an InitializeFromRequest not being castable from an Entity to an early bound type.

I'm really not sure if this is a bug or just a misunderstanding on my part of how I should be declaring the proxy type assembly at the start of the test.

The code works when deployed to CRM and an almost identical integration test works too.

The code that's failing looks like this:
`private static bsp_usl_disbursement CreateDisbursement(Guid loanID, IOrganizationService service)
        {

            InitializeFromRequest request = new InitializeFromRequest
            {
                TargetEntityName = bsp_usl_disbursement.EntityLogicalName,
                EntityMoniker = new EntityReference(bsp_usl_loan.EntityLogicalName, loanID)
            };

            InitializeFromResponse response = (InitializeFromResponse)service.Execute(request);

            return (bsp_usl_disbursement)response.Entity;

        }`
		
I get System.InvalidCastException: Unable to cast object of type 'Microsoft.Xrm.Sdk.Entity' to type 'USLoans.Plugins.Entities.bsp_usl_disbursement'	where I try to cast response.Entity to the early bound 'bsp_usl_disbursement entity.

I'm initializing my Context in the tests like this.
Context = new XrmFakedContext() { ProxyTypesAssembly = Assembly.GetAssembly(typeof(bsp_usl_loan)) };	
(bsp_usl_loan is in the same class as bsp_usl_disbursement)

I think I'm doing everthing pretty much as you are doing it in your test class InitializeFromRequestTests.

I can try and write a unit test for this, but wondered if you had any ideas what I might be doing wrong before I do this?

Thanks as ever for any suggestions.

Ben

**Comment by jordimontana82** [comment]
Hi Ben,

I'm good thanks! And you? :)

I think the issue is that the fake message is [creating instances of dynamic entities](https://github.com/jordimontana82/fake-xrm-easy/blob/master/FakeXrmEasy.Shared/FakeMessageExecutors/InitializeFromRequestExecutor.cs#L39-L43) regardless of ProxyTypesAssembly being set to use early bound. I think it should create an instance of a specific sublcass if ProxyTypesAssembly is != null basically.

So yeah, it's a bug.

Besides, just for clarification, you only need to manually set ProxyTypesAssembly in unit tests if using early bound, and not calling .Initialize. If you are calling .Initialize() with early bound classes, ProxyTypesAssembly will be set internally.

**Comment by jordimontana82** [comment]
It should probably create an instance following [this example](https://github.com/jordimontana82/fake-xrm-easy/blob/6f909ba025087ab03af6551baed689647eb36378/FakeXrmEasy.Shared/Extensions/EntityExtensions.cs#L117-L122) from the extension methods to clone entities.

Do you want to maybe fix it in your fork and issue a PR?

**Comment by bwmodular** [comment]
Yes, I'd love to have a go at fixing it. I'll create a test for it and then see if I can fix it. That example is pretty clear, so it should be relatively straightforward.

**Comment by jordimontana82** [comment]
Yeah, it should be fairly simple, if you could add 2 unit tests, one for dynamic entities and another one for early bound it would be amazing :)  

Thanks a mill!
