### ISSUE TITLE
Initalize() doesn't allow late-bound instances after early-bound instances

### ISSUE THREAD

**Issue by teppolainio** [jordimontana82/fake-xrm-easy#263]
I noticed there seems to be assumption on method protected internal void AddEntity(Entity e) on class FakeXrmEasy.XrmFakedContext that requires one call XrmFakedContext.Initialize() so that late-bound instances are given before any early-bound instances.

When first early-bound instance is hit on FakeXrmEasy.XrmFakedContext.AddEntity() property ProxyTypesAssembly is set to non-null value which effectively causes exception "Couldnt find reflected type for {0}" to be thrown for all late-bound entities given to Initialize().

Example:
```
var lateBound = new Entity("asdf") {
  Attributes = new AttributeCollection() {  ... initialize attributes ... }
};

var earlyBound = new Account() {
  Name = "Test account"
};

// This goes through without problems
var success = new List<Entity>() {
  lateBound,
  earlyBound
};
var fakedContext = new XrmFakedContext();
fakedContext.Initialize(success);

// This will throw exception "Couldnt find reflected type for asdf"
var failure = new List<Entity>() {
  earlyBound,
  lateBound
};
var fakedContext2 = new XrmFakedContext();
fakedContext2.Initialize(failure);
```

Two questions:
1. Is this intentional? I hope not.
2. Could implementation always use initialized metadata instead of using proxy types assembly when initializing faked context? See below for suggestion.

Currently  `XrmFakedContext.InitializeMetadata()` seems to populate only property `XrmFakedContext.EntityMetadata` and method `XrmFakedContext.AddEntity()` (called by `Initialize()`) seems to populate property `XrmFakedContext.AttributeMetadataNames. I had assumed `InitializeMetadata()` would've populated also attribute metadata.

Would it be problem if both `InitializeMetadata()` and `Initialize()` would populate values to properties `EntityMetadata` and `AttributeMetadataNames`? This effectively would allow writing of `Initialize()` independent of ProxyTypesAssembly because it could check all data from two aforementioned properties. I also think this might have something in common with #247

**Comment by jordimontana82** [comment]
Hi @teppolainio, you can use early bound and late bound at the same time, however, keep in mind once early bound is set, the late bound entity must also be generated in the ProxyTypesAssembly assembly, 

This is by design right now.

Once ProxyTypesAssembly is set, is enforcing that even late bound entities should exist in the generated assembly.

Another option would be to rely exclusively on late bound, but you would loose the benefits of strongly typed code.

I see your point about just considering EntityMetadata, but right now the purpose of InitializeMetadata is to only use it for unit testing metadata messages (i.e. RetrieveEntityRequest, RetrieveAttributeRequest, InsertOptionSetValue, etc). Having to inject metadata for all scenarios would make unit tests bigger, a bit more complex to maintain. Deserialising metadata is also very very slow.

**Comment by khorozhansky** [comment]
Hi Jordi,
Sorry for raising this topic again.
I would vote for this feature as well because sometime there may be a need to use early-bound along with late-bound and it's not quite convenient to generate dummy proxy for this.
Is it some that too difficult to change?
Thanks

**Comment by FixRM** [comment]
+1 Faced this problem today
