### ISSUE TITLE
Execution time earlybound versus latebound

### ISSUE THREAD

**Issue by AxelPajot** [jordimontana82/fake-xrm-easy#282]
Hi ! thanks you for your great work first, i have been working with Crm 365 for 1 month now and i started doing unit test recently, this is also the first time I'm using early bound.

My question is : is it normal that early bound takes really more time to execute than late bound (about 10x more) when I'm doing unit test.

I generated the CrmSvcUtil with Early bound generator from XrmToolBox and added it to the solution.

**Comment by eNeRGy164** [comment]
The code is doing a lot of reflection work on execution when there is an early bound assembly. That might be a source.

I tried to optimize a part of this, but that broke @jordimontana82's release build. I still need to investigate why that happened.

**Comment by jordimontana82** [comment]
Indeed, it is doing a lot of reflection but I don't think it is increasing it to up to 10x.... anyway, could you maybe post a sample unit test so we can investigate?

Cheers!

**Comment by jordimontana82** [comment]
@eNeRGy164 re the broken build I fixed it some time ago, there was a compilation symbol missing in the build.fsx, that's why that build script was producing a different output than appveyor. Re performance yeah, early will be slower. 

For me I prefer the benefits of early bound (i.e. break the build early), even if it is slower, specially when you could use parallel execution.
