### ISSUE TITLE
Easy Loading of Complex  Context

### ISSUE THREAD

**Issue by LHPiney** [jordimontana82/fake-xrm-easy#313]
Hello ! 

I have a question, is there some easy way to load a complex contex ? i mean using some external file like json can load on the init of the test and set a contex with all values, an entities. 

In some scenarios  set the initiall context definition in a programmatic way is too complex, and not very maintainable. Pherhaps we can build just a wrapper to do this on our test, an store the definition files like an asset.

Thanks, Luis.

**Comment by jordimontana82** [comment]
Hi Luis!

Thx! There's nothing built-in for that as of yet....  What kind of data are you trying to initialise?

If you need to load too many records it might be an indicator something needs to be refactored a bit more ... I usually break it down into smaller classes, and if the unit tests are like variations of almost the same data (i.e. it only changes one attribute) you can always refactor that initialisation in a separate method with the "common data" and only change whatever it's needed for each test.

If the data is in code, it could easily renamed / refactore too, something it might be more complex if it was in a json file. Besides, reading data from disk will make tests much more slower... so that's why I'd like to understand your scenario :)

**Comment by LHPiney** [comment]
Hello Jordi, 

Let me ty to explain, i need to make a test with a Quote, with several lines and custom entities linked to each one of them. In some case we hace Quotes with more than 50 - 60 lines. 
 
Is not the need to have a lot of entities, but the complexity of some of thoses.

Thanks a lot, Luis

**Comment by jordimontana82** [comment]
Ok, no worries.

Do you have to have the 50 - 60 records in the one test? Or can you test the logic with only 2 or 3 records for example. Sometimes a small number of records is needed to test many scenarios.

Anyway it shouldn't be a big deal to deserialize a json file  as a dictionary, and then assign the dictionary to the Attributes property of an entity for example.

string json = @"{""key1"":""value1"",""key2"":""value2""}";

var values = JsonConvert.DeserializeObject<Dictionary<string, string>>(json);

And put in a method like InitializeFromFile(pathToJson) ?

Do you fancy a PR? :D

**Comment by LHPiney** [comment]
Great ! i'll try

**Comment by jordimontana82** [comment]
Hi Luis!

Any joy with this? :)

**Comment by BetimBeja** [comment]
Hello Jordi, 
to actually serialize/deserialize Json the library would need an unnecessary dependency on [Newtonsoft.Json](https://github.com/JamesNK/Newtonsoft.Json). Personally i don't think it is a good idea to have the test data in an external file because it makes it difficult to reason about the test case.

If @LHPiney still needs a way to load the context from a file or a json string, i can share a small project which can serialize/deserialize an Entity or List<Entity> with Newtonsoft.Json, even though it hasn't been tested much and might need some tweaking.

Best regards,
Betim.

**Comment by jordimontana82** [comment]
I agree with @BetimBeja about adding probably not needed extra dependencies.

You have the option to serialize / deserialize  in your unit test project if needed... so I'm closing this one.

I did something similar in other projects to also deserialize metadata so I see it as something optional external to the scope of this project.

**Comment by FixRM** [comment]
Hello @LHPiney,

I can highly recommend you use Data driven tests for that purpose. Implementation depends on testing framework you use, but they are similar. This is MSTest2 implementation: https://docs.microsoft.com/en-us/visualstudio/test/how-to-create-a-data-driven-unit-test?view=vs-2017. After all, plugins, as well as workflow activities, are basically a number of input and output parameters and data between them. The idea here is to write single test and pass a number of input and output parameters combination into it. Also it lets you to separate your test logic and test data itself. I believe it's is something you are looking for.

**Comment by bwmodular** [comment]
Hi @LHPiney, I'm with @FixRM on this one. Data Driven testing is a good approach for this. See my post in another repo about some of the different tools you could use for this:
https://github.com/Microsoft/EasyRepro/issues/284

**Comment by BetimBeja** [comment]
I am sure data driven is a good approach for testing different inputs for the same algorithm.
This issue is more about loading a single complex context, which I don't know if SpecFlow is suitable for because I haven't used it for this use case before. What I know for sure is that you can serialize an Entity collection and EntityMetadata collection with my Library XrmEntitySerializer :) so you can have a complex context saved from CRM to json and use that in your test case. Still not a big fan of this approach because you can't be sure of the quality of test data.
Best regards,
Betim.
