### ISSUE TITLE
Raised the Pull Request, 

### ISSUE THREAD

**Issue by patnamayyappa** [jordimontana82/fake-xrm-easy#322]
i don't have idea to include reviewers, can any one review my pull request "321" shows as below
![image](https://user-images.githubusercontent.com/10165638/42145170-46846b02-7ddd-11e8-855e-12dc083bef0b.png)

push to master and provide the latest nuget package to proceed with my org unit test cases, we are blocked because of this issue. (around 40+ test cases are failing). 

help me with actual procedure to push the code if i done anythin wrong. thanks in advance. :)

**Comment by jordimontana82** [comment]
Hi @patnamayyappa 

That's the correct procedure, once the pull request has been submitted it needs to be reviewed and approved.

It has been merged now and it will be available in v1.45.1 

If you're in a hurry, rather than waiting for a PR to be merged you could clone your own fork and reference it while the PR is being reviewed ....
