### ISSUE TITLE
Weird way of adding inputs to the code activity

### ISSUE THREAD

**Issue by ArsenAghajanyan** [jordimontana82/fake-xrm-easy#363]
Hello,

This is not an issue nor a bug, I just would like to make sure this is laid properly. I've just noticed that the way we're adding custom input parameters to the code activity is a bit weird. 
Say we have something like this in the code activity:

`[Input("POLines")]`
`public InArgument<string> POLinesString { get; set; }`

The way we're able to provide this input is the following:

`Dictionary<string, object> inputs = new Dictionary<string, object>()`
`{`
        `{"POLinesString", JSONSerialize(POLines)}`
`};`

My question is why do we need to provide 'POLinesString' name as a key in the dictionary and not 'POLines'. The second one would make more sense in my opinion as the code activity is waiting for the input called POLines and it maps it to the POLinesString. It should not wait for the input called POLinesString directly. 
Am I wrong? Would be glad to hear your thought regarding this :) Thanks!

Regards,
Arsen.

**Comment by jordimontana82** [comment]
Exactly, the other properties in Input/Output attributes are meant to be used as the Labels displayed on CRM's UI really, which may contain whitespaces even, so that's why WorkflowInvoker just looks at the property names instead.

Maybe would be beneficial to just add a comment to the signature of ExecuteCodeActivity method to reflect this, it's just a training issue one would have for the first time really it tries to execute a code activity only : ) .
