### ISSUE TITLE
Fake XRM Easy passing Entity metadata does not retrieve Labels

### ISSUE THREAD

**Issue by victorsolaya** [jordimontana82/fake-xrm-easy#433]
I am trying to initialize the Metadata with FakeXRMEasy like this: 

```c#
XrmContext.InitializeMetadata(System.Reflection.Assembly.GetAssembly(typeof(MyEntity)));
```
When I try to do 

```c#
RetrieveEntityRequest retrieveEntityRequest = new RetrieveEntityRequest
{
         EntityFilters = EntityFilters.Attributes,
         LogicalName = MyEntity.EntityLogicalName
};
RetrieveEntityResponse retrieveMyEntityEntityResponse = (RetrieveEntityResponse)service.Execute(retrieveEntityRequest);
 EntityMetadata MyEntityEntity = retrieveMyEntityEntityResponse.EntityMetadata;
```
The MyEntityEntity.Attributes[0].DisplayName is null.

Do I have to initialize something in the first XrmContext ?

**Comment by BetimBeja** [comment]
Hello Victor,
the ability to generate the metadata from the early bound entities has been added with PR #396, but I didn't think of mapping the `DisplayName` property, if you have an idea on how to do that in a meaningful way please issue a PR :)
Best regards,
Betim.

**Comment by victorsolaya** [comment]
Oh, I see.
I will try to do that, meanwhile, is there any label that we could use as help wanted, waiting PR...?
BTW, thanks for the quick answer!

**Comment by BetimBeja** [comment]
Hello Victor,
Unfortunately labels are controlled by Jordi, I guess he will add the `enhancement` and `help wanted` labels. 
If you have any Idea how to do this issue a PR with the fix and I can help finish your changes if there is the need. No labels are needed for this. 😄 

Best regards,
Betim.

**Comment by jordimontana82** [comment]
Hi Victor,

I don't think we can extract the DisplayName information from the generated proxy assemblies since that .dll doesn't carry over the DisplayName information, just basic information about types, relationships and enums I believe.

I believe is you need the DisplayNames you should use a different approach (i.e. exporting Metadata, serializing into disk, and read from there)... or else suggest an improvement to crmsvcutil to generate that and we could incorporate that into Betim's PR, or else, manually injecting the DisplayNames just for testing purposes might be the easiest... :)

I'm closing this one now.
