### ISSUE TITLE
Fake Calls?

### ISSUE THREAD

**Issue by daryllabar** [jordimontana82/fake-xrm-easy#54]
Does FakeXrmEasy support Faking out an Xrm Call?  Lets say for example I have a really complicated query in my plugin that requires 4 or 5 entities to be created, but I actually want to test the update statement that comes after that. 

Here is an example of how I would do it in XrmUnitTest currently:
``` csharp
service = new OrganizationServiceBuilder(service).WithFakeRetrieveMultiple(
    (s, q) =>
    {
        var col = new EntityCollection();
        col.Entities.Add(myEntity);
        return col;
    }).Build();
```

So this says, if you have a RetrieveMultiple return myEntity instead of actually performing a query

**Comment by DigitalFlow** [comment]
Yes, you can just add an execution mock for this.
Something like that:

''C#
fakedContext.AddExecutionMock<RetrieveMultipleRequest>(req => {
return new RetrieveMultipleResponse{
Entities = new EntityCollection { myEntity }
}
});
''
There might be minor differences in the implementation, but it should give you a clue.

Kind regards,
Florian

**Comment by jordimontana82** [comment]
Hi @daryllabar 

Yep, as @DigitalFlow  it is indeed possible.

Lambda expressions are convenient for mocks in a specific test. If you wanna have the same behavior across tests another option would be to refactor that in a [FakeMessageExecutor](https://github.com/jordimontana82/fake-xrm-easy/blob/b0c7228537759a754c595553a2d65918e8fb1b48/FakeXrmEasy.Tests.Shared/FakeContextTests/FakeContextMockTests.cs#L77-L77) class.

Even if you have those 2 choices, I still prefer to use test data, and like 4 o 5 entities in a context via .Initialize(), cause it forces you to think of the possible different scenarios. One of the key things of the framework is that allows complex queries, like using many levels of joins, with filters, orders, etc, so that you could also test those complex things by just using test data.
