### ISSUE TITLE
Couldnt find reflected type for sdkmessageprocessingstepimage

### ISSUE THREAD

**Issue by alan50** [jordimontana82/fake-xrm-easy#605]
When trying to register a plugin image together with a plugin I get the following error:
""Couldnt find reflected type for sdkmessageprocessingstepimage"

The code to register plugin looks like this:
`fakeCrmContext.RegisterPluginStep<Donna.Crm.Domain.Plugins.OccasionPlugin.OnPostUpdate>
 (new PluginStepDefinition() { 
MessageName = "Update", 
EntityLogicalName = Occasion.EntityLogicalName, 
Stage = ProcessingStepStage.Postoperation, 
Mode = ProcessingStepMode.Asynchronous, 
FilteringAttributes = new string[]{"pdg_code","pdg_gratificationtext","pdg_campaignactivity"}, 
ImagesDefinitions = new PluginImageDefinition[]{ new PluginImageDefinition("preEntityImage", ProcessingStepImageType.PreImage) }})`

I m using D365 onprem v.9 and the following FakeXRMEasy Packages:
FakeXrmEasy.v9 2.3.0
FakeXrmEasy.Plugins.v9 2.3.0
FakeXrmEasy.Abstractions.v9 2.3.0

The registration works fine as long as I dont add an Image to it. 
Can you help with this? Many thanks!!!

**Comment by jordimontana82** [comment]
Hi Alan,

Thanks a mill for raising this issue. That issue was resolved in version 2.3.2: https://github.com/DynamicsValue/fake-xrm-easy-plugins/blob/2x-dev/CHANGELOG.md

You need to either generate sdkmessageprocessingstepimage as part of your early bound entities, or let FakeXrmEasy use them for you, but not both, to avoid confusion. 

Please give that version a go and let me know.

Also bear in mind this repo is for v1 of FakeXrmEasy and it's deprecated, we're tracking all new stuff in the new repo for versions v2 and above at https://github.com/DynamicsValue/fake-xrm-easy.

**Comment by jordimontana82** [comment]
@alan50  more info about the specific issue and how it was addressed....

https://github.com/DynamicsValue/fake-xrm-easy/issues/95
