### ISSUE TITLE
Support for context.SaveChanges, Add etc

### ISSUE THREAD

**Issue by craigseymour** [jordimontana82/fake-xrm-easy#71]
Jordi - I wondered if you were planning to add support for methods such as SaveChanges, Add, Delete etc to XrmFakedContext?

**Comment by jordimontana82** [comment]
Hi @craigseymour 

Thanks a mill for your question :) 

It is actually not needed. With the already faked instance of the IOrganizationService you can create an instance of an OrgServiceContext which will call the Create, Update, Delete, etc methods indirectly, when doing .AddObject and .SaveChanges, for example.

[Here](https://github.com/jordimontana82/fake-xrm-easy/blob/master/FakeXrmEasy.Tests.Shared/FakeContextTests/OrgServiceContextTests/OrgServiceContextTests.cs)'s an example

**Comment by craigseymour** [comment]
Ah - I see.  So we make a context from the service from the context from ... 💫 

Thanks for your help!

**Comment by jordimontana82** [comment]
No worries... yeah maybe it's a bit misleading because of the name given to the XrmFaked"Context" : )

But the XrmFakedContext is not the OrgServiceContext, but the place to store entities in a repository and the entry point for executing plugins, code activities, and mainly, get a reference to the faked service you can pass everywhere .

**Comment by craigseymour** [comment]
All is clear - sorry for being a bit slow on the uptake.  The name **is** confusing for simple folk like me, but I'm not sure what else you would call it really.  It's for Xrm.  It's Fake.  And it's a Context.  So other than calling it XrmFakeContextButNotTheOrgServiceContext...

**Comment by jordimontana82** [comment]
No problem :+1:
