### ISSUE TITLE
Bug in Service Update

### ISSUE THREAD

**Issue by DigitalFlow** [jordimontana82/fake-xrm-easy#9]
Hey Jordi,

just found a bug in the "FakeUpdate" method of XrmFakedContext.Crud:
When you send an updated Entity with the IOrganizationService.Update method, you only set those attributes if you want to change. In the FakeUpdate method you set the whole context object to the update object that was passed in, so that old values that should not have been changed by the update (and thus where not set in the update object) are being deleted.
As a fix, we should take the context object and map all fields that the update object contains onto it.
This fix should be rather easy, but I'm currently having difficulties getting the project build, since there are problems with the NuGet packages.

Kind Regards,
DigitalFlow

**Comment by jordimontana82** [comment]
Hey @DigitalFlow 

Thanks a mill for spotting the issue.

I've pushed a new version which fixes this as well as 2 new units tests.

What issues do you have with the NuGet packages, btw?

**Comment by DigitalFlow** [comment]
Hey @jordimontana82,

thanks for fixing this issue. I managed to resolve all NuGet problems that I had and am now able to build the solution myself, too.
Now I'll be able to make some changes, I'll send you some Pull Requests from my fork when I'm done :)

**Comment by jordimontana82** [comment]
Great!

Looking forward :+1:

**Comment by jordimontana82** [comment]
Hi @DigitalFlow ,

I've just merged an old pending branch for 2013. I didn't want to merge it initially because there was 1 test failing but I suppose it is better to merge it first and fix the test later, given that you are going to make changes soon.

The idea is to have the main code in the FakeXrmEasy and FakeXrmEasy.Tests projects, and then, 2 separate projects per Xrm version (i.e. FakeXrmEasy.2013, and FakeXrmEasy.Tests.2013) so we could reuse as much code as possible across versions and use conditional compilation for the different parts, if needed.
